/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AdminLayout: typeof import('./src/components/admin-layout.vue')['default']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BaseButton: typeof import('./src/components/common/buttons/BaseButton.vue')['default']
    BaseForm: typeof import('./src/components/common/form/BaseForm.vue')['default']
    CodeEdit: typeof import('./src/components/html-editor/CodeEdit.vue')['default']
    DragNDrop: typeof import('./src/components/files/drag-n-drop.vue')['default']
    DragNDropArea: typeof import('./src/components/files/drag-n-drop-area.vue')['default']
    HeaderPage: typeof import('./src/components/header-page.vue')['default']
    HtmlEdit: typeof import('./src/components/html-editor/HtmlEdit.vue')['default']
    HtmlEditor: typeof import('./src/components/html-editor/HtmlEditor.vue')['default']
    HtmlPreview: typeof import('./src/components/html-editor/HtmlPreview.vue')['default']
    LoadingIcon: typeof import('./src/components/common/buttons/LoadingIcon.vue')['default']
    MbDropdownContainer: typeof import('./src/components/mb-dropdown-container.vue')['default']
    MbHr: typeof import('./src/components/mb-hr.vue')['default']
    MbLine: typeof import('./src/components/mb-line.vue')['default']
    MultiLangInput: typeof import('./src/components/multi-lang-input.vue')['default']
    Notification: typeof import('./src/components/common/NotificationPlugin/Notification.vue')['default']
    Notifications: typeof import('./src/components/common/NotificationPlugin/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/files/select.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    ZLabel: typeof import('./src/components/z-label.vue')['default']
  }
}
